on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ORG_ID: "937800926639"
      PROJECT_ID: terraform-projects-gcp-483285
      TF_BUCKET: 900097363476-tfstate
      BILLING_ACCOUNT_ID: 0116EA-2A299B-BFF97D
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ env.TF_BUCKET }}"
      - name: Terraform Apply
        id: plan
        run: terraform apply -auto-approve -no-color -var "gh_pat=${{ secrets.GH_PAT }}" -var "org_id=${{ env.ORG_ID }}" -var "project_id=${{ env.PROJECT_ID }}" -var "billing_account_id=${{ env.BILLING_ACCOUNT_ID }}"
